version: '3.8'

services:
  frontend:
    build: ./rim_frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend

  backend:
    build: ./rim_backend
    ports:
      - "4000:4000"
      - "8080:8080"
    depends_on:
      - database
    environment:
      MONGO_URL: mongodb://database:27017/database

  database:
    image: mongo
    ports:
      - "27017:27017"
