version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    ports:
      - "8080:8080"
      - "4000:4000"
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
